main: clp.zkaleejoo.ClearLagPlus
version: ${project.version}
name: ClearLagPlus
author: ZkAleeJoo
api-version: 1.19

commands:
  clearlagplus:
    description: ClearLagPlus main command - reload, clear, get
    aliases: [clp]

permissions:
  clearlagplus.admin:
    description: Administrator permissions for ClearLagPlus
    default: op